name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - experimental

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional: build step if you use a build system
      # - name: Build project
      #   run: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ # or ./build if you have a build folder
          destination_dir: ${{ github.ref == 'refs/heads/experimental' && 'experimental' || '' }}
